
# PyPI:
from dotenv import load_dotenv
import openai
from openai import OpenAI

load_dotenv()

# Local:
from common.config import chatgpt_35_turbo
from common.config import env_vars

openai.api_key = env_vars['OPENAI_KEY']

model = chatgpt_35_turbo['name']

def generate_response(system_prompt: str, user_prompt: str, model: str) -> str:
        """
        Generate a response from the chatbot model.

        Args:
            system_prompt (str): The initial prompt for the system.
            user_prompt (str): The user input.

        Returns:
            str: The response generated by the chatbot.
        """

        client = OpenAI(api_key=env_vars['OPENAI_KEY'])

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

        response = client.chat.completions.create(
            model=model, messages=messages, stream=False, temperature=0
        )
        return response.choices[0].message.content